### PR TITLE
fix: store session info in localstorage

### PR DESCRIPTION
**Pull request by solomonng2001**
* try submitting code and refresh the browser
- previously, the attempted status will be changed to not attempted on refresh
- now, the attempted status will remain attempted on refresh

### CODE REVIEW

**Review by UnwilledTangent — APPROVED** [review]
I can confirm. Session status does remain attempted after refresh. lgtm.

**Comment by bensohh** [comment]
> I can confirm. Session status does remain attempted after refresh. lgtm.

@UnwilledTangent can you try to pull the same branch again and retest it? made a fix to the merge conflict

**Comment by UnwilledTangent** [comment]
testing now

**Comment by UnwilledTangent** [comment]
yep, does remain attempted

**Pull request merged**
